substitute-path:
  # - {from: "/compiler/machine/directory", to: "/debugger/machine/directory"}
  - {from: "/home/jaychen/go/src/github.com/Kong/kong-mesh", to: "/Users/jaychen/go/src/github.com/Kong/kong-mesh"}
  - {from: "/home/jaychen/go/src/github.com/Kong/kuma", to: "/Users/jaychen/go/src/github.com/Kong/kuma"}
  - {from: "/home/jaychen/go/pkg/mod/github.com/kumahq/kuma@v0.0.0-20240219152353-23764bbca70d", to: "/Users/jaychen/go/src/github.com/Kong/kuma"}
  - {from: "/home/jaychen/go/pkg/mod", to: "/Users/jaychen/go/pkg/mod"}