#cloud-config

users:
  - default
  - name: vmadmin
    sudo:  ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - AAAAB3NzaC1yc2EAAAADAQABAAABgQCwj0pBhXB2ZykwUwN1xt4kWkl39Aggo1Vr/uypVVHTHc3LSVrP0zGDkEmFYNKcjsU4HFvMETnrvCYu5zLfW+viJeRN0xLK/ObNu8EdC6UmVti9+3Bc4DB0uKBuz3HADdtM1AMuGVIPeX1q4aLGgEOu7dMlpSZrACGMmaFEy5cOmO9PkyvxY+DL90VK85XJna7CeV40KVN1h+ihQdNnOX9F8t9NDbbl/MhrJ4LVN7Ar5+VVa413ICveMsOkgZh8LXfztPKwjoYNFPqAF/Rxp6EAkV0EHKh4Fhw3rpg9IW6LZQys2ZH+QJRQFG3k3vzQBTTgNr54GENVz7mzc90l8VYatyN927xw/2sRJiIItSlshVlt0ciRRbOm2kJXV4e+P6G5AEQzp17nH6Cfxy90SyIZQ8gZPXZA8kmDNP4R8gdZcX9GV8YIQm9vyF1Yk+YI09WFmshnJZQjbDoDpe9dizSfb8om4HoF8OEEazoIqyrPAhkGzw5byFLviTG/V1VDLRE=

package_update: true
package_upgrade: true

packages:
- python3-pip
- ruby-full
- jq
- sysstat
- zsh
- fzf
- sshfs

snap:
  commands:
  - snap install yq
  - snap install multipass-sshfs
  - snap install go --channel=1.21/stable --classic
  - snap install docker --channel=core18/stable
  - snap refresh

runcmd:
- DEBIAN_FRONTEND=noninteractive apt-get remove -y landscape-client landscape-common adwaita-icon-theme humanity-icon-theme
- DEBIAN_FRONTEND=noninteractive apt-get -y upgrade
- DEBIAN_FRONTEND=noninteractive apt-get -y autoremove

- |
  # disable unnecessary services
  systemctl disable man-db.timer man-db.service --now
  systemctl disable apport.service apport-autoreport.service  --now
  systemctl disable apt-daily.service apt-daily.timer --now
  systemctl disable apt-daily-upgrade.service apt-daily-upgrade.timer --now
  systemctl disable unattended-upgrades.service --now
  systemctl disable motd-news.service motd-news.timer --now
  systemctl disable bluetooth.target --now
  systemctl disable ua-messaging.service ua-messaging.timer --now
  systemctl disable ua-timer.timer ua-timer.service --now
  systemctl disable systemd-tmpfiles-clean.timer --now

  # Disable IPv6
  echo "net.ipv6.conf.all.disable_ipv6=1" | tee -a /etc/sysctl.conf
  echo "net.ipv6.conf.default.disable_ipv6=1" | tee -a /etc/sysctl.conf
  echo "net.ipv6.conf.lo.disable_ipv6=1" | tee -a /etc/sysctl.conf
  sysctl -p

- |
  # oh-my-zsh
  sudo -u jaychen sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  sudo -u jaychen git clone https://github.com/zsh-users/zsh-autosuggestions.git ~jaychen/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  sudo -u jaychen git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~jaychen/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
  sudo -u jaychen sed -i 's/plugins=(git)/plugins=(fzf git zsh-autosuggestions zsh-syntax-highlighting virtualenv colored-man-pages kubectl colorize)/g' ~jaychen/.zshrc
  sudo -u jaychen echo 'export PATH=$PATH:$HOME/.local/bin' >> ~jaychen/.zshrc

- |
  # change default shell
  sudo chsh -s /bin/zsh jaychen

- |
  # dev tools
  curl -o /usr/bin/kubectl -L https://dl.k8s.io/release/v1.28.3/bin/linux/amd64/kubectl
  curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 && chmod 700 get_helm.sh && ./get_helm.sh && rm ./get_helm.sh
  
  addgroup --system docker
  adduser jaychen docker
  newgrp docker
  snap disable docker
  snap enable docker

- |
  # dev workspace
  sudo -u jaychen mkdir -p ~jaychen/go/src/github.com/jijiechen
  sudo -u jaychen git clone git@github.com:jijiechen/kuma.git ~jaychen/go/src/github.com/jijiechen/kuma
  sudo -u jaychen git clone git@github.com:jijiechen/kuma-gui.git ~jaychen/go/src/github.com/jijiechen/kuma-gui
  
  sudo -u jaychen mkdir -p ~jaychen/go/src/github.com/Kong
  sudo -u jaychen git clone git@github.com:Kong/kong-mesh.git ~jaychen/go/src/github.com/Kong/kong-mesh
  sudo -u jaychen git clone git@github.com:Kong/kong-mesh-gui.git ~jaychen/go/src/github.com/Kong/kong-mesh-gui



final_message: "The system is up and ready, initialization took $UPTIME seconds"


# Example: https://github.com/Abuelodelanada/charm-dev-utils/blob/main/cloud-init/charm-dev-juju-latest-edge.yaml