#cloud-config

users:
  - default
  - name: VM_USERNAME
    sudo:  ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - SSH_PUBLIC_KEY

package_update: true
package_upgrade: true

packages:
- python3-pip
- ruby-full
- jq
- sysstat
- zsh
- fzf
- sshfs
- clang-format

snap:
  commands:
  - snap install yq
  - snap install multipass-sshfs
  - snap install go --channel=1.21/stable --classic
  - snap install docker --channel=core18/stable
  - snap refresh

runcmd:
- DEBIAN_FRONTEND=noninteractive apt-get remove -y landscape-client landscape-common adwaita-icon-theme humanity-icon-theme
- DEBIAN_FRONTEND=noninteractive apt-get -y upgrade
- DEBIAN_FRONTEND=noninteractive apt-get -y autoremove

- |
  # disable unnecessary services
  systemctl disable man-db.timer man-db.service --now
  systemctl disable apport.service apport-autoreport.service  --now
  systemctl disable apt-daily.service apt-daily.timer --now
  systemctl disable apt-daily-upgrade.service apt-daily-upgrade.timer --now
  systemctl disable unattended-upgrades.service --now
  systemctl disable motd-news.service motd-news.timer --now
  systemctl disable bluetooth.target --now
  systemctl disable ua-messaging.service ua-messaging.timer --now
  systemctl disable ua-timer.timer ua-timer.service --now
  systemctl disable systemd-tmpfiles-clean.timer --now

  # Disable IPv6
  echo "net.ipv6.conf.all.disable_ipv6=1" | tee -a /etc/sysctl.conf
  echo "net.ipv6.conf.default.disable_ipv6=1" | tee -a /etc/sysctl.conf
  echo "net.ipv6.conf.lo.disable_ipv6=1" | tee -a /etc/sysctl.conf
  
  # Increment inotify limit
  echo "fs.inotify.max_user_watches = 524288" | tee -a /etc/sysctl.conf
  sysctl -p

- |
  # oh-my-zsh
  sudo -u VM_USERNAME sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  sudo -u VM_USERNAME git clone https://github.com/zsh-users/zsh-autosuggestions.git ~VM_USERNAME/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  sudo -u VM_USERNAME git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~VM_USERNAME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
  sudo -u VM_USERNAME sed -i 's/plugins=(git)/plugins=(fzf git zsh-autosuggestions zsh-syntax-highlighting virtualenv colored-man-pages kubectl colorize)/g' ~VM_USERNAME/.zshrc
  sudo -u VM_USERNAME echo 'export PATH=$PATH:$HOME/.local/bin' >> ~VM_USERNAME/.zshrc

  # change default shell
  sudo chsh -s /bin/zsh VM_USERNAME


- |
  # dev tools
  curl -o /usr/bin/kubectl -L https://dl.k8s.io/release/v1.28.3/bin/linux/amd64/kubectl
  curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 && chmod 700 get_helm.sh && ./get_helm.sh && rm ./get_helm.sh
  
  addgroup --system docker
  adduser VM_USERNAME docker
  newgrp docker
  snap disable docker
  snap enable docker

- |
  # dev workspace (git clone requires ssh keys to be setup)
  sudo -u VM_USERNAME mkdir -p ~VM_USERNAME/go/src/github.com/Kong
  sudo -u VM_USERNAME mkdir -p ~VM_USERNAME/go/src/github.com/kumahq
  sudo -u VM_USERNAME git clone https://github.com/kumahq/kuma.git ~VM_USERNAME/go/src/github.com/kumahq/kuma
  sudo -u VM_USERNAME (cd ~VM_USERNAME/go/src/github.com/kumahq/kuma ; make dev/tools)
 
  # an incorrect /etc/environment file can cause misbehaved OS, and then `multipass ls` can also be misbehave
  echo 'PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/VM_USERNAME/.kuma-dev/kuma-master/bin"' > /etc/environment

final_message: "The system is up and ready, initialization took $UPTIME seconds"


# Example: https://github.com/Abuelodelanada/charm-dev-utils/blob/main/cloud-init/charm-dev-juju-latest-edge.yaml