#!/bin/bash


RUN_MODE=${RUN_MODE:-all-in-one}
SERVICE_NAME=${SERVICE_NAME:-echo-server}
SERVICE_PORT=${SERVICE_PORT:-10011}
SERVICE_PROTOCOL=${SERVICE_PROTOCOL:-http}

WORKING_DIR=/tmp/${RANDOM}
mkdir -p ${WORKING_DIR}

SERVICE_NAME=${SERVICE_NAME} SERVICE_PORT=${SERVICE_PORT} SERVICE_PROTOCOL=${SERVICE_PROTOCOL} RUN_MODE=${RUN_MODE} /kuma/run-app.sh &
SERVICE_NAME=${SERVICE_NAME} SERVICE_PORT=${SERVICE_PORT} SERVICE_PROTOCOL=${SERVICE_PROTOCOL} RUN_MODE=${RUN_MODE} WORKING_DIR=${WORKING_DIR} /kuma/run-dp.sh &
WORKING_DIR=${WORKING_DIR} RUN_MODE=${RUN_MODE} /kuma/run-cp.sh &

function exit_all {
    kill -15 $(jobs -p) > /dev/null 2>&1 || true
}

trap exit_all EXIT INT QUIT TERM

sleep infinity
